### ISSUE TITLE
Add instructions by code challenge type for Java

### ISSUE THREAD

**Issue by brookr** [codefellows/data-structures-and-algorithms#11]

**Comment by edy-cf** [comment]
Note to self: also needs a folder structure (use C# as an example but of course many things will be different due to being created by Gradle).

**Comment by edy-cf** [comment]
@brookr @johncokos Shoot, I'm a dummy and pushed directly to main. Sorry about that! Please review the commit and let me know if you see any issues: https://github.com/codefellows/data-structures-and-algorithms/commit/acdc6929ee170c51e7536d7a8073ab4b22e915b3

**Comment by brookr** [comment]
You are no dummy, you've found a flaw in the repo settings! I've corrected it, thanks for highlighting the issue. 

I'll leave it to John to review the commit.
