### ISSUE TITLE
Add challenge README template 

### ISSUE THREAD

**Issue by JB-Tellez** [codefellows/data-structures-and-algorithms#14]
Supply students with DSA Challenge/Lab example README.

E.g.

# Daily Code Challenge README Example

## Perfect Sequence
*Author: Fix-It Felix*

---

### Problem Domain
***[Problem Domain for the Code Challenge]***

Given an array. Return "Yes" if the sequence is considered a perfect sequence. Otherwise, return "No"

---

### Inputs and Expected Outputs

| Input | Expected Output |
| :----------- | :----------- |
| [1,3,2] | Yes |
| [2,99,100] | No |

---

### Big O

| Time | Space |
| :----------- | :----------- |
| O(n) | O(n) |

---

### Whiteboard Visual
***[Your Whiteboard Image]***
![Image 1](https://via.placeholder.com/750x500)

---

### Change Log
***[The change log will list any changes made to the code base. This includes any changes from TA/Instructor feedback]***  
1.3: *Added new passing tests for Contains method* - 17 Nov 2020  
1.2: *Fixed bug where Next relation was being lost on Insert* - 14 Nov 2020  
1.1: *Fixed formatting for the Print method* - 13 Nov 2020  

---

**Comment by brookr** [comment]
Example README is given in the code challenge assignments.
