### ISSUE TITLE
Hidden files / Unzipping

### ISSUE THREAD

**Issue by JB-Tellez** [codefellows/data-structures-and-algorithms#2]
Instructions have students download then extract a zip. This ends up with a nested folder. No biggie, just copy the stuff up a folder and delete original folder along with the zip. But the hidden files often don't get copied up if student is using finder. That means github actions, linting, etc. get lost which messes CI up.

So need some instrux about that. Or we have them fork/clone instead. Was there an issue with forking to begin with?

**Comment by brookr** [comment]
New approach means this is no longer an issue.
