### ISSUE TITLE
Add a proof-of-life test file and an Action to show this structure works for Java

### ISSUE THREAD

**Issue by brookr** [codefellows/data-structures-and-algorithms#7]

**Comment by edy-cf** [comment]
Depends on #11, so do that one first.

**Comment by edy-cf** [comment]
Hopefully fixed with https://github.com/codefellows/data-structures-and-algorithms/pull/55

**Comment by edy-cf** [comment]
Nope, build failed. Need to debug a bit...

**Comment by edy-cf** [comment]
Now fixed. Should be good to merge that PR, and afterwards, this issue can be closed.
